//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("AccountsDBModel", "AAA", "efPayee", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(AccountsCore.efPayee), "tblEntre", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AccountsCore.tblEntre), true)]

#endregion

namespace AccountsCore
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class AccountsDBEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new AccountsDBEntities object using the connection string found in the 'AccountsDBEntities' section of the application configuration file.
        /// </summary>
        public AccountsDBEntities() : base("name=AccountsDBEntities", "AccountsDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AccountsDBEntities object.
        /// </summary>
        public AccountsDBEntities(string connectionString) : base(connectionString, "AccountsDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AccountsDBEntities object.
        /// </summary>
        public AccountsDBEntities(EntityConnection connection) : base(connection, "AccountsDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<efPayee> efPayees
        {
            get
            {
                if ((_efPayees == null))
                {
                    _efPayees = base.CreateObjectSet<efPayee>("efPayees");
                }
                return _efPayees;
            }
        }
        private ObjectSet<efPayee> _efPayees;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<efCatagory> efCatagories
        {
            get
            {
                if ((_efCatagories == null))
                {
                    _efCatagories = base.CreateObjectSet<efCatagory>("efCatagories");
                }
                return _efCatagories;
            }
        }
        private ObjectSet<efCatagory> _efCatagories;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblEntre> tblEntres
        {
            get
            {
                if ((_tblEntres == null))
                {
                    _tblEntres = base.CreateObjectSet<tblEntre>("tblEntres");
                }
                return _tblEntres;
            }
        }
        private ObjectSet<tblEntre> _tblEntres;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblGroup> tblGroups
        {
            get
            {
                if ((_tblGroups == null))
                {
                    _tblGroups = base.CreateObjectSet<tblGroup>("tblGroups");
                }
                return _tblGroups;
            }
        }
        private ObjectSet<tblGroup> _tblGroups;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblAccount> tblAccounts
        {
            get
            {
                if ((_tblAccounts == null))
                {
                    _tblAccounts = base.CreateObjectSet<tblAccount>("tblAccounts");
                }
                return _tblAccounts;
            }
        }
        private ObjectSet<tblAccount> _tblAccounts;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblProperte> tblPropertes
        {
            get
            {
                if ((_tblPropertes == null))
                {
                    _tblPropertes = base.CreateObjectSet<tblProperte>("tblPropertes");
                }
                return _tblPropertes;
            }
        }
        private ObjectSet<tblProperte> _tblPropertes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblTaxCode> tblTaxCodes
        {
            get
            {
                if ((_tblTaxCodes == null))
                {
                    _tblTaxCodes = base.CreateObjectSet<tblTaxCode>("tblTaxCodes");
                }
                return _tblTaxCodes;
            }
        }
        private ObjectSet<tblTaxCode> _tblTaxCodes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblTtest01> tblTtest01
        {
            get
            {
                if ((_tblTtest01 == null))
                {
                    _tblTtest01 = base.CreateObjectSet<tblTtest01>("tblTtest01");
                }
                return _tblTtest01;
            }
        }
        private ObjectSet<tblTtest01> _tblTtest01;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the efPayees EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToefPayees(efPayee efPayee)
        {
            base.AddObject("efPayees", efPayee);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the efCatagories EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToefCatagories(efCatagory efCatagory)
        {
            base.AddObject("efCatagories", efCatagory);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblEntres EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblEntres(tblEntre tblEntre)
        {
            base.AddObject("tblEntres", tblEntre);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblGroups EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblGroups(tblGroup tblGroup)
        {
            base.AddObject("tblGroups", tblGroup);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblAccounts EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblAccounts(tblAccount tblAccount)
        {
            base.AddObject("tblAccounts", tblAccount);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblPropertes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblPropertes(tblProperte tblProperte)
        {
            base.AddObject("tblPropertes", tblProperte);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblTaxCodes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblTaxCodes(tblTaxCode tblTaxCode)
        {
            base.AddObject("tblTaxCodes", tblTaxCode);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblTtest01 EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblTtest01(tblTtest01 tblTtest01)
        {
            base.AddObject("tblTtest01", tblTtest01);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AccountsDBModel", Name="efCatagory")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class efCatagory : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new efCatagory object.
        /// </summary>
        /// <param name="catagoryId">Initial value of the CatagoryId property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="income">Initial value of the income property.</param>
        /// <param name="propertySpecific">Initial value of the PropertySpecific property.</param>
        /// <param name="groupId">Initial value of the GroupId property.</param>
        /// <param name="taxCodeId">Initial value of the TaxCodeId property.</param>
        /// <param name="obsolete">Initial value of the Obsolete property.</param>
        /// <param name="system">Initial value of the System property.</param>
        public static efCatagory CreateefCatagory(global::System.Guid catagoryId, global::System.String name, global::System.Boolean income, global::System.Boolean propertySpecific, global::System.Guid groupId, global::System.Guid taxCodeId, global::System.Boolean obsolete, global::System.Boolean system)
        {
            efCatagory efCatagory = new efCatagory();
            efCatagory.CatagoryId = catagoryId;
            efCatagory.Name = name;
            efCatagory.income = income;
            efCatagory.PropertySpecific = propertySpecific;
            efCatagory.GroupId = groupId;
            efCatagory.TaxCodeId = taxCodeId;
            efCatagory.Obsolete = obsolete;
            efCatagory.System = system;
            return efCatagory;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid CatagoryId
        {
            get
            {
                return _CatagoryId;
            }
            set
            {
                if (_CatagoryId != value)
                {
                    OnCatagoryIdChanging(value);
                    ReportPropertyChanging("CatagoryId");
                    _CatagoryId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CatagoryId");
                    OnCatagoryIdChanged();
                }
            }
        }
        private global::System.Guid _CatagoryId;
        partial void OnCatagoryIdChanging(global::System.Guid value);
        partial void OnCatagoryIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean income
        {
            get
            {
                return _income;
            }
            set
            {
                OnincomeChanging(value);
                ReportPropertyChanging("income");
                _income = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("income");
                OnincomeChanged();
            }
        }
        private global::System.Boolean _income;
        partial void OnincomeChanging(global::System.Boolean value);
        partial void OnincomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean PropertySpecific
        {
            get
            {
                return _PropertySpecific;
            }
            set
            {
                OnPropertySpecificChanging(value);
                ReportPropertyChanging("PropertySpecific");
                _PropertySpecific = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PropertySpecific");
                OnPropertySpecificChanged();
            }
        }
        private global::System.Boolean _PropertySpecific;
        partial void OnPropertySpecificChanging(global::System.Boolean value);
        partial void OnPropertySpecificChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid GroupId
        {
            get
            {
                return _GroupId;
            }
            set
            {
                OnGroupIdChanging(value);
                ReportPropertyChanging("GroupId");
                _GroupId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GroupId");
                OnGroupIdChanged();
            }
        }
        private global::System.Guid _GroupId;
        partial void OnGroupIdChanging(global::System.Guid value);
        partial void OnGroupIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid TaxCodeId
        {
            get
            {
                return _TaxCodeId;
            }
            set
            {
                OnTaxCodeIdChanging(value);
                ReportPropertyChanging("TaxCodeId");
                _TaxCodeId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TaxCodeId");
                OnTaxCodeIdChanged();
            }
        }
        private global::System.Guid _TaxCodeId;
        partial void OnTaxCodeIdChanging(global::System.Guid value);
        partial void OnTaxCodeIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Obsolete
        {
            get
            {
                return _Obsolete;
            }
            set
            {
                OnObsoleteChanging(value);
                ReportPropertyChanging("Obsolete");
                _Obsolete = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Obsolete");
                OnObsoleteChanged();
            }
        }
        private global::System.Boolean _Obsolete;
        partial void OnObsoleteChanging(global::System.Boolean value);
        partial void OnObsoleteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean System
        {
            get
            {
                return _System;
            }
            set
            {
                OnSystemChanging(value);
                ReportPropertyChanging("System");
                _System = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("System");
                OnSystemChanged();
            }
        }
        private global::System.Boolean _System;
        partial void OnSystemChanging(global::System.Boolean value);
        partial void OnSystemChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AccountsDBModel", Name="efPayee")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class efPayee : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new efPayee object.
        /// </summary>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="obsolete">Initial value of the Obsolete property.</param>
        /// <param name="system">Initial value of the System property.</param>
        /// <param name="payeeId">Initial value of the PayeeId property.</param>
        public static efPayee CreateefPayee(global::System.String name, global::System.Boolean obsolete, global::System.Boolean system, global::System.Guid payeeId)
        {
            efPayee efPayee = new efPayee();
            efPayee.Name = name;
            efPayee.Obsolete = obsolete;
            efPayee.System = system;
            efPayee.PayeeId = payeeId;
            return efPayee;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Obsolete
        {
            get
            {
                return _Obsolete;
            }
            set
            {
                OnObsoleteChanging(value);
                ReportPropertyChanging("Obsolete");
                _Obsolete = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Obsolete");
                OnObsoleteChanged();
            }
        }
        private global::System.Boolean _Obsolete;
        partial void OnObsoleteChanging(global::System.Boolean value);
        partial void OnObsoleteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean System
        {
            get
            {
                return _System;
            }
            set
            {
                OnSystemChanging(value);
                ReportPropertyChanging("System");
                _System = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("System");
                OnSystemChanged();
            }
        }
        private global::System.Boolean _System;
        partial void OnSystemChanging(global::System.Boolean value);
        partial void OnSystemChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid PayeeId
        {
            get
            {
                return _PayeeId;
            }
            set
            {
                if (_PayeeId != value)
                {
                    OnPayeeIdChanging(value);
                    ReportPropertyChanging("PayeeId");
                    _PayeeId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PayeeId");
                    OnPayeeIdChanged();
                }
            }
        }
        private global::System.Guid _PayeeId;
        partial void OnPayeeIdChanging(global::System.Guid value);
        partial void OnPayeeIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AccountsDBModel", "AAA", "tblEntre")]
        public EntityCollection<tblEntre> tblEntres
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tblEntre>("AccountsDBModel.AAA", "tblEntre");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tblEntre>("AccountsDBModel.AAA", "tblEntre", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AccountsDBModel", Name="tblAccount")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblAccount : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblAccount object.
        /// </summary>
        /// <param name="accountId">Initial value of the AccountId property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="ownership">Initial value of the Ownership property.</param>
        /// <param name="type">Initial value of the Type property.</param>
        /// <param name="hidden">Initial value of the Hidden property.</param>
        /// <param name="lockedUntil">Initial value of the LockedUntil property.</param>
        /// <param name="reconciledOn">Initial value of the ReconciledOn property.</param>
        /// <param name="lock">Initial value of the Lock property.</param>
        public static tblAccount CreatetblAccount(global::System.Guid accountId, global::System.String name, global::System.String ownership, global::System.String type, global::System.Boolean hidden, global::System.DateTime lockedUntil, global::System.DateTime reconciledOn, global::System.String @lock)
        {
            tblAccount tblAccount = new tblAccount();
            tblAccount.AccountId = accountId;
            tblAccount.Name = name;
            tblAccount.Ownership = ownership;
            tblAccount.Type = type;
            tblAccount.Hidden = hidden;
            tblAccount.LockedUntil = lockedUntil;
            tblAccount.ReconciledOn = reconciledOn;
            tblAccount.Lock = @lock;
            return tblAccount;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid AccountId
        {
            get
            {
                return _AccountId;
            }
            set
            {
                if (_AccountId != value)
                {
                    OnAccountIdChanging(value);
                    ReportPropertyChanging("AccountId");
                    _AccountId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("AccountId");
                    OnAccountIdChanged();
                }
            }
        }
        private global::System.Guid _AccountId;
        partial void OnAccountIdChanging(global::System.Guid value);
        partial void OnAccountIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Ownership
        {
            get
            {
                return _Ownership;
            }
            set
            {
                OnOwnershipChanging(value);
                ReportPropertyChanging("Ownership");
                _Ownership = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Ownership");
                OnOwnershipChanged();
            }
        }
        private global::System.String _Ownership;
        partial void OnOwnershipChanging(global::System.String value);
        partial void OnOwnershipChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Type
        {
            get
            {
                return _Type;
            }
            set
            {
                OnTypeChanging(value);
                ReportPropertyChanging("Type");
                _Type = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Type");
                OnTypeChanged();
            }
        }
        private global::System.String _Type;
        partial void OnTypeChanging(global::System.String value);
        partial void OnTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Hidden
        {
            get
            {
                return _Hidden;
            }
            set
            {
                OnHiddenChanging(value);
                ReportPropertyChanging("Hidden");
                _Hidden = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Hidden");
                OnHiddenChanged();
            }
        }
        private global::System.Boolean _Hidden;
        partial void OnHiddenChanging(global::System.Boolean value);
        partial void OnHiddenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime LockedUntil
        {
            get
            {
                return _LockedUntil;
            }
            set
            {
                OnLockedUntilChanging(value);
                ReportPropertyChanging("LockedUntil");
                _LockedUntil = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LockedUntil");
                OnLockedUntilChanged();
            }
        }
        private global::System.DateTime _LockedUntil;
        partial void OnLockedUntilChanging(global::System.DateTime value);
        partial void OnLockedUntilChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime ReconciledOn
        {
            get
            {
                return _ReconciledOn;
            }
            set
            {
                OnReconciledOnChanging(value);
                ReportPropertyChanging("ReconciledOn");
                _ReconciledOn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ReconciledOn");
                OnReconciledOnChanged();
            }
        }
        private global::System.DateTime _ReconciledOn;
        partial void OnReconciledOnChanging(global::System.DateTime value);
        partial void OnReconciledOnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Lock
        {
            get
            {
                return _Lock;
            }
            set
            {
                OnLockChanging(value);
                ReportPropertyChanging("Lock");
                _Lock = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Lock");
                OnLockChanged();
            }
        }
        private global::System.String _Lock;
        partial void OnLockChanging(global::System.String value);
        partial void OnLockChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AccountsDBModel", Name="tblEntre")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblEntre : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblEntre object.
        /// </summary>
        /// <param name="entryId">Initial value of the EntryId property.</param>
        /// <param name="description">Initial value of the Description property.</param>
        /// <param name="date">Initial value of the Date property.</param>
        /// <param name="recieptNo">Initial value of the RecieptNo property.</param>
        /// <param name="amount">Initial value of the Amount property.</param>
        /// <param name="payeeId">Initial value of the PayeeId property.</param>
        /// <param name="catagoryId">Initial value of the CatagoryId property.</param>
        /// <param name="propertyId">Initial value of the PropertyId property.</param>
        /// <param name="transferAccountId">Initial value of the TransferAccountId property.</param>
        /// <param name="accountId">Initial value of the AccountId property.</param>
        public static tblEntre CreatetblEntre(global::System.Guid entryId, global::System.String description, global::System.DateTime date, global::System.String recieptNo, global::System.Decimal amount, global::System.Guid payeeId, global::System.Guid catagoryId, global::System.Guid propertyId, global::System.Guid transferAccountId, global::System.Guid accountId)
        {
            tblEntre tblEntre = new tblEntre();
            tblEntre.EntryId = entryId;
            tblEntre.Description = description;
            tblEntre.Date = date;
            tblEntre.RecieptNo = recieptNo;
            tblEntre.Amount = amount;
            tblEntre.PayeeId = payeeId;
            tblEntre.CatagoryId = catagoryId;
            tblEntre.PropertyId = propertyId;
            tblEntre.TransferAccountId = transferAccountId;
            tblEntre.AccountId = accountId;
            return tblEntre;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid EntryId
        {
            get
            {
                return _EntryId;
            }
            set
            {
                if (_EntryId != value)
                {
                    OnEntryIdChanging(value);
                    ReportPropertyChanging("EntryId");
                    _EntryId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("EntryId");
                    OnEntryIdChanged();
                }
            }
        }
        private global::System.Guid _EntryId;
        partial void OnEntryIdChanging(global::System.Guid value);
        partial void OnEntryIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Date
        {
            get
            {
                return _Date;
            }
            set
            {
                OnDateChanging(value);
                ReportPropertyChanging("Date");
                _Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Date");
                OnDateChanged();
            }
        }
        private global::System.DateTime _Date;
        partial void OnDateChanging(global::System.DateTime value);
        partial void OnDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RecieptNo
        {
            get
            {
                return _RecieptNo;
            }
            set
            {
                OnRecieptNoChanging(value);
                ReportPropertyChanging("RecieptNo");
                _RecieptNo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("RecieptNo");
                OnRecieptNoChanged();
            }
        }
        private global::System.String _RecieptNo;
        partial void OnRecieptNoChanging(global::System.String value);
        partial void OnRecieptNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Amount
        {
            get
            {
                return _Amount;
            }
            set
            {
                OnAmountChanging(value);
                ReportPropertyChanging("Amount");
                _Amount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Amount");
                OnAmountChanged();
            }
        }
        private global::System.Decimal _Amount;
        partial void OnAmountChanging(global::System.Decimal value);
        partial void OnAmountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid PayeeId
        {
            get
            {
                return _PayeeId;
            }
            set
            {
                OnPayeeIdChanging(value);
                ReportPropertyChanging("PayeeId");
                _PayeeId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PayeeId");
                OnPayeeIdChanged();
            }
        }
        private global::System.Guid _PayeeId;
        partial void OnPayeeIdChanging(global::System.Guid value);
        partial void OnPayeeIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid CatagoryId
        {
            get
            {
                return _CatagoryId;
            }
            set
            {
                OnCatagoryIdChanging(value);
                ReportPropertyChanging("CatagoryId");
                _CatagoryId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CatagoryId");
                OnCatagoryIdChanged();
            }
        }
        private global::System.Guid _CatagoryId;
        partial void OnCatagoryIdChanging(global::System.Guid value);
        partial void OnCatagoryIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid PropertyId
        {
            get
            {
                return _PropertyId;
            }
            set
            {
                OnPropertyIdChanging(value);
                ReportPropertyChanging("PropertyId");
                _PropertyId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PropertyId");
                OnPropertyIdChanged();
            }
        }
        private global::System.Guid _PropertyId;
        partial void OnPropertyIdChanging(global::System.Guid value);
        partial void OnPropertyIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid TransferAccountId
        {
            get
            {
                return _TransferAccountId;
            }
            set
            {
                OnTransferAccountIdChanging(value);
                ReportPropertyChanging("TransferAccountId");
                _TransferAccountId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TransferAccountId");
                OnTransferAccountIdChanged();
            }
        }
        private global::System.Guid _TransferAccountId;
        partial void OnTransferAccountIdChanging(global::System.Guid value);
        partial void OnTransferAccountIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid AccountId
        {
            get
            {
                return _AccountId;
            }
            set
            {
                OnAccountIdChanging(value);
                ReportPropertyChanging("AccountId");
                _AccountId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AccountId");
                OnAccountIdChanged();
            }
        }
        private global::System.Guid _AccountId;
        partial void OnAccountIdChanging(global::System.Guid value);
        partial void OnAccountIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AccountsDBModel", "AAA", "efPayee")]
        public efPayee tblPayee
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<efPayee>("AccountsDBModel.AAA", "efPayee").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<efPayee>("AccountsDBModel.AAA", "efPayee").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<efPayee> tblPayeeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<efPayee>("AccountsDBModel.AAA", "efPayee");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<efPayee>("AccountsDBModel.AAA", "efPayee", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AccountsDBModel", Name="tblGroup")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblGroup : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblGroup object.
        /// </summary>
        /// <param name="groupId">Initial value of the GroupId property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="obsolete">Initial value of the Obsolete property.</param>
        /// <param name="system">Initial value of the System property.</param>
        public static tblGroup CreatetblGroup(global::System.Guid groupId, global::System.String name, global::System.Boolean obsolete, global::System.Boolean system)
        {
            tblGroup tblGroup = new tblGroup();
            tblGroup.GroupId = groupId;
            tblGroup.Name = name;
            tblGroup.Obsolete = obsolete;
            tblGroup.System = system;
            return tblGroup;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid GroupId
        {
            get
            {
                return _GroupId;
            }
            set
            {
                if (_GroupId != value)
                {
                    OnGroupIdChanging(value);
                    ReportPropertyChanging("GroupId");
                    _GroupId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("GroupId");
                    OnGroupIdChanged();
                }
            }
        }
        private global::System.Guid _GroupId;
        partial void OnGroupIdChanging(global::System.Guid value);
        partial void OnGroupIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Obsolete
        {
            get
            {
                return _Obsolete;
            }
            set
            {
                OnObsoleteChanging(value);
                ReportPropertyChanging("Obsolete");
                _Obsolete = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Obsolete");
                OnObsoleteChanged();
            }
        }
        private global::System.Boolean _Obsolete;
        partial void OnObsoleteChanging(global::System.Boolean value);
        partial void OnObsoleteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean System
        {
            get
            {
                return _System;
            }
            set
            {
                OnSystemChanging(value);
                ReportPropertyChanging("System");
                _System = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("System");
                OnSystemChanged();
            }
        }
        private global::System.Boolean _System;
        partial void OnSystemChanging(global::System.Boolean value);
        partial void OnSystemChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AccountsDBModel", Name="tblProperte")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblProperte : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblProperte object.
        /// </summary>
        /// <param name="propertyId">Initial value of the PropertyId property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="obsolete">Initial value of the Obsolete property.</param>
        /// <param name="system">Initial value of the System property.</param>
        public static tblProperte CreatetblProperte(global::System.Guid propertyId, global::System.String name, global::System.Boolean obsolete, global::System.Boolean system)
        {
            tblProperte tblProperte = new tblProperte();
            tblProperte.PropertyId = propertyId;
            tblProperte.Name = name;
            tblProperte.Obsolete = obsolete;
            tblProperte.System = system;
            return tblProperte;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid PropertyId
        {
            get
            {
                return _PropertyId;
            }
            set
            {
                if (_PropertyId != value)
                {
                    OnPropertyIdChanging(value);
                    ReportPropertyChanging("PropertyId");
                    _PropertyId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PropertyId");
                    OnPropertyIdChanged();
                }
            }
        }
        private global::System.Guid _PropertyId;
        partial void OnPropertyIdChanging(global::System.Guid value);
        partial void OnPropertyIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Obsolete
        {
            get
            {
                return _Obsolete;
            }
            set
            {
                OnObsoleteChanging(value);
                ReportPropertyChanging("Obsolete");
                _Obsolete = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Obsolete");
                OnObsoleteChanged();
            }
        }
        private global::System.Boolean _Obsolete;
        partial void OnObsoleteChanging(global::System.Boolean value);
        partial void OnObsoleteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean System
        {
            get
            {
                return _System;
            }
            set
            {
                OnSystemChanging(value);
                ReportPropertyChanging("System");
                _System = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("System");
                OnSystemChanged();
            }
        }
        private global::System.Boolean _System;
        partial void OnSystemChanging(global::System.Boolean value);
        partial void OnSystemChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AccountsDBModel", Name="tblTaxCode")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblTaxCode : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblTaxCode object.
        /// </summary>
        /// <param name="taxCodeId">Initial value of the TaxCodeId property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="obsolete">Initial value of the Obsolete property.</param>
        /// <param name="system">Initial value of the System property.</param>
        public static tblTaxCode CreatetblTaxCode(global::System.Guid taxCodeId, global::System.String name, global::System.Boolean obsolete, global::System.Boolean system)
        {
            tblTaxCode tblTaxCode = new tblTaxCode();
            tblTaxCode.TaxCodeId = taxCodeId;
            tblTaxCode.Name = name;
            tblTaxCode.Obsolete = obsolete;
            tblTaxCode.System = system;
            return tblTaxCode;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid TaxCodeId
        {
            get
            {
                return _TaxCodeId;
            }
            set
            {
                if (_TaxCodeId != value)
                {
                    OnTaxCodeIdChanging(value);
                    ReportPropertyChanging("TaxCodeId");
                    _TaxCodeId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("TaxCodeId");
                    OnTaxCodeIdChanged();
                }
            }
        }
        private global::System.Guid _TaxCodeId;
        partial void OnTaxCodeIdChanging(global::System.Guid value);
        partial void OnTaxCodeIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Obsolete
        {
            get
            {
                return _Obsolete;
            }
            set
            {
                OnObsoleteChanging(value);
                ReportPropertyChanging("Obsolete");
                _Obsolete = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Obsolete");
                OnObsoleteChanged();
            }
        }
        private global::System.Boolean _Obsolete;
        partial void OnObsoleteChanging(global::System.Boolean value);
        partial void OnObsoleteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean System
        {
            get
            {
                return _System;
            }
            set
            {
                OnSystemChanging(value);
                ReportPropertyChanging("System");
                _System = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("System");
                OnSystemChanged();
            }
        }
        private global::System.Boolean _System;
        partial void OnSystemChanging(global::System.Boolean value);
        partial void OnSystemChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AccountsDBModel", Name="tblTtest01")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblTtest01 : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblTtest01 object.
        /// </summary>
        /// <param name="taxCodeId">Initial value of the TaxCodeId property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="obsolete">Initial value of the Obsolete property.</param>
        /// <param name="system">Initial value of the System property.</param>
        public static tblTtest01 CreatetblTtest01(global::System.Guid taxCodeId, global::System.String name, global::System.Boolean obsolete, global::System.Boolean system)
        {
            tblTtest01 tblTtest01 = new tblTtest01();
            tblTtest01.TaxCodeId = taxCodeId;
            tblTtest01.Name = name;
            tblTtest01.Obsolete = obsolete;
            tblTtest01.System = system;
            return tblTtest01;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid TaxCodeId
        {
            get
            {
                return _TaxCodeId;
            }
            set
            {
                if (_TaxCodeId != value)
                {
                    OnTaxCodeIdChanging(value);
                    ReportPropertyChanging("TaxCodeId");
                    _TaxCodeId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("TaxCodeId");
                    OnTaxCodeIdChanged();
                }
            }
        }
        private global::System.Guid _TaxCodeId;
        partial void OnTaxCodeIdChanging(global::System.Guid value);
        partial void OnTaxCodeIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Obsolete
        {
            get
            {
                return _Obsolete;
            }
            set
            {
                OnObsoleteChanging(value);
                ReportPropertyChanging("Obsolete");
                _Obsolete = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Obsolete");
                OnObsoleteChanged();
            }
        }
        private global::System.Boolean _Obsolete;
        partial void OnObsoleteChanging(global::System.Boolean value);
        partial void OnObsoleteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean System
        {
            get
            {
                return _System;
            }
            set
            {
                OnSystemChanging(value);
                ReportPropertyChanging("System");
                _System = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("System");
                OnSystemChanged();
            }
        }
        private global::System.Boolean _System;
        partial void OnSystemChanging(global::System.Boolean value);
        partial void OnSystemChanged();

        #endregion
    
    }

    #endregion
    
}
